apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    resolver 10.96.0.10 valid=10s;
    
    server { listen 80; server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Serve static assets directly
    location /static/ {
        alias /usr/share/nginx/html/static/;
        expires 1h;
        add_header Cache-Control "public";
    }

    # Proxy API to backend service
    location /api/ {
        set $backend backend:8000;
        proxy_pass http://$backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Forward Authorization token if you use it (DRF token/JWT)
        proxy_set_header Authorization $http_authorization;

        proxy_redirect off;
    }

    # Redirect /admin -> /admin/
    location = /admin {
        return 301 /admin/;
    }

    # Proxy Django admin to backend service
    location /admin/ {
        set $backend backend:8000;
        proxy_pass http://$backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Authorization $http_authorization;

        proxy_redirect off;
    }

    # Frontend routes (SPA-style)
    # If you DON'T want SPA behavior, change the last part to "=404"
    location / {
        try_files $uri $uri/ /index.html;
    }

    }
  